<?php
@define("_binhluan","즐기며 먹다");
@define("_trongluong","무게");
@define("_no_post","기사가 업데이트 중입니다. 나중에 다시 오십시오.");
@define("_hoidap","질문과 답변");
define("_thoigiannhan", "수신 시간");
define("_tinhthanh", "지방");
define("_quanhuyen", "지구");
define("_tieude", "제목");
define("_dangkylienhe", "등록 연락처");
define("_xaydung", "빌드");
define("_xinchao", "안녕하세요");
define("_tuyendung", "채용");
define("_setting_slogan",$row_setting["slogan_vi"]);
define("_setting_email",$row_setting["email"]);
define("_setting_diachi",$row_setting["diachi_vi"]);
define("_dichvu", "서비스");
define("_vechungtoi", "회사 소개");
define("_step", "단계");
define("_madonhang", "주문 코드");
define("_mavandon", "선하 증권");
define("_thongtin_nguoigui", "발신자 정보");
define("_nguoigui_ten", "성명");
define("_nguoigui_diachi", "주소");
define("_nguoigui_dienthoai", "전화");
define("_thongtin_nguoinhan", "받는 사람 정보");
define("_nguoinhan_ten", "성명");
define("_nguoinhan_diachi", "주소");
define("_nguoinhan_dienthoai", "전화");

define('_tracuuvandon', '선하 증권 조회');
define('_tranvandon', '검색');
define('_header_hotline_label', 'Contact Hotline');
define('_quytrinh', '물류 프로세스');
define('_dichvu_title', '우리의 서비스');
define('_danhmuc_dichvu', '서비스 디렉토리');
define('_newsletter_title', '문의 견적');
define('_newsletter_desc', '배달 통지를 받거나 추가 정보가 필요하면 아래 양식을 작성하십시오');
define('_hotline_label', '필요한 경우 문의하십시오');
define('_mxh_bottom', 'Link MXH');
define('_thuvien', '라이브러리');
define('_trochoi', '게임');
define('_lophoc', '교실');
define('_dieukhoan', '약관 및 약속');
define('_bando', '지도');
define('_sanphamdacbiet', '특별한 제품');
define('_tintucmoinhat', '최신 뉴스');
define('_chinhsachhotro', '지원 정책');
define('_thongtinchitiet', '세부 사항');
define('_mota', '설명');
define('_sanphamnoibat', '뜨거운 제품');
define('_nhamay', '공장');
define('_congty', '회사');
define('_thanhphanchinh', '주요 구성 요소');
define('_mangxahoi', '소셜 네트워크');
define('_ 통통 산팜', '제품 정보');
define('_bandodiadiem', '회사 위치지도');
define('_tensp', '제품 이름');
define('_ngaytruycap', '액세스 날짜');
define('_dangky', '가입');
define('_nhantinmoi', '새로운 정보 및 프로모션을 받으려면 가입하십시오');
define('_kinhnghiemnhanong', '농민 체험');
define('_dknhantin', '뉴스를 수신하려면 이메일을 입력하십시오 ...');
define('_tintucnoibat', '핫 뉴스');
define('_dathang', '주문');
define('_ngaycapnhat', '업데이트 날짜');
define('_xuatxu', '원산지');
define('_giaban', '가격');
define('_chitietbanggia', '가격표 세부 정보');
define('_daxem', '보임');
define('_dangluc', '게시일');
define('_ngonngu', '언어');
define('_logodoitac', '파트너 로고');
define('_sanphamcungloai', '기타 제품');
define('_quahopmail', '비아 우편함');
define('_chungnhan', '인증');
define('_bando', '지도');
define('_thaoluan', '토론');
define('_ngay', '일');
define('_phut', '분');
define('_chunhat', '일요일');
define('_thubay', '토요일');
define('_thusau', '금요일');
define('_thunam', '목요일');
define('_thutu', '수요일');
define('_thuba', '화요일');
define('_thuhai', '월요일');
define('_khachhangdoitac', '고객-파트너');
define('_tinnhanh', '빠른 뉴스');
define('_tinhhinhhd', '상황 상황');
define('_보기','더보기»');
define('_thuvienanh', '갤러리');
define('_khuyenmai', '프로모션');
define('_lhchungtoi', '문의하기');
define('_chongia', '가격 선택');
define('_chonmausac', '색상 선택');
define('_chonchatlieu', '재료 선택');
define('_nhaptensp', '제품 이름 입력');

define('_ketquatimkiem', '검색 결과');
define('_sanphambanchay', '최고의 판매자 제품');
define('_kienthuc', '지식');
define('_duan', '프로젝트');
define('_duannoibat', '추천 프로젝트');
define('_giohang', '쇼핑 카트');
define('_muatiep', '다음 구매');
define('_xoatatca', '모두 삭제');
define('_capnhat', '업데이트');



define('_spkhac', '기타 제품');
define('_luotxem', '조회수');
define('_xemtatca', '모두보기');
define('_thongtinlienhe', '연락처 정보');
define('_danhmucsanpham', '제품 카테고리');
define('_baogia', '가격표 받기');
define('_nhaptu', '검색 !!!');
define('_maso', '코드');
define('_homnay', '오늘');
define('_tuanhientai', '이번 주');
define('_thanghientai', '현재 월');
define('_all', '총 연극');


define('_phanphoi', '배포자');
define('_gtcongty', '회사 소개');
define('_chiase', '공유');
define('_dangtruycap', '온라인');
define('_tongonline', 'Sum');
define('_xemtiep', '더 읽기');
define('_sanphammoi', '신제품');
define('_sanphamtieubieu', '일반 제품');
define('_cactinkhac', '기타 뉴스');
define('_dienthoaituvan', '상담 전화');
define('_hotlinetuvan', '컨설팅 핫라인');
define('_gui', '보내기');
define('_nhaplai', '다시 입력');

define('_chunhat', '일요일');
define('_thuhai', '월요일');
define('_thuba', '화요일');
define('_thutu', '수요일');
define('_thunam', '목요일');
define('_thusau', '사중주');
define('_chubay', '토요일');

//------------ Menu -----------------
define('_trangchu', '홈');
define('_gioithieu', '소개');
define('_hinhcty', '회사 이미지');
define('_cocau', '조직 구조');
define('_sanpham', '제품');
define('_tintuc', '뉴스');
define('_dichvu', '서비스');
define('_doitac', '파트너');
define('_map', '지도');
define('_tuyendung', '채용');
define('_congtrinh', '건설');
define('_lienhe', '연락처');
define('_thongtincty', '회사 정보');
define('_timkiem', '검색');
define('_tukhoa', '검색');
define('_lienket', '링크');
define('_tienich', '웹 사이트 위젯');
define('_doitac', '파트너');
define('_ngaydang', '날짜 게시');
define('_hinhanh', '이미지');
define('_banggia', '가격표');
define('_huongdan', '사용 지침');
define('_ 통통 추 엔 호안', '이전 정보');
define('_thietbichothue', '임대 장비');
define('_chitietthietbichothue', '임대 장비 세부 사항');
//---------------- Left ----------------
define('_muahang', '구매');
define('_newproduct', '새 제품');
define('_sanphamtieubieu', '일반 제품');
define('_chitietsanpham', '제품 정보');
define('_counter', '액세스 통계');
define('_totalvisits', '방문자수 :');
define('_chontheo', '브랜드 별 선택');
define('_thuongkhac', '기타 브랜드');
define('_nhapsp', '검색 할 제품을 입력하십시오.');
define('_chungkhoan', '증권');
define('_ngoaite', '외국 통화');
define('_giavang', '골드 가격');
define('_thoitiet', '날씨');
define('_hinhanhdep', '아름다운 이미지');
define('_gioithieucongty', '회사 소개');
define('_sukiendatochuc', '조직 된 이벤트');
define('_chitietsukiendatochuc', '이벤트 세부 사항 개최');
define('_danhmuc', '임대 장비 목록');
//--------------- Center ----------------
define('_giovn','images/giohang.gif');
define('_guiok','media/images/ok.gif');
define('_reset','media/images/btn_nhaplai.gif');

define('_photocompany','Hình ảnh công ty');
define('_projectdetails','Chi tiết dự án');
define('_otherproducts','Các sản phẩm khác');
define('_readmore','Xem tiếp...');
define('_chitiettintuc','Chi tiết tin tức');
define('_cacbaivietkhac','Các bài viết khác');
define('_projects','Các dự án');
define('_contact','Liên hệ');
define('_chitiet','세부 사항보기');

define('_cungdm','danh mục Sản phẩm ');
define('_ptxemay','PHỤ TÙNG XE MÁY');
define('_sanphamxemay','Sản Phẩm Xe Máy');

//--------------- Right ----------------
define('_onlinesupport', '온라인 지원');
define('_video', '비디오');
define('_ 충치', '인증서');
define('_hotrotructuyen', '온라인 지원');
define('_hotro', '지원');
define('_thongke', '통계');
define('_Quangcao', '광고');
define('_online', '온라인');
define('_truycap', '이미 온라인');
define('_sukien', '이벤트');
define('_Dichvu', '서비스');
define('_dssanpham', '제품 목록');
define('_thongtinlienhe', '연락처 정보');
define('_thongtinkhachhang', '고객 정보');
define('_Hethong', '시스템 HEAD');
define('_tinnb', '하이라이트');
define('_baohanh', '유지 보수 보증');
define('_masp', 'MSSP');
define('_Trove', '[돌아 가기]');
define('_Kichthuoc', '치수');
define('_thietbitieubieu', '일반 렌탈 장비');
//---------------- Footer ---------------
define('_thanhvien','Đối Tác - Công Ty Thành Viên');
define('_web','Thiết Kế web');
define('_diachi','주소 ');
define('_dienthoai','전화 ');
define('_tongtruycap','전체 액세스');
define('_truso','Trụ Sở Chính ');
define('_vanphong','Chi Nhánh');
define('_thongketruycap','액세스 통계');
define('_tuan','Thống kê tuần');
define('_thang','Thống kê tháng');
define('_tongsotruycap','Tổng');
define('_songuoitruycap','Số người truy cập');
//------------- Contact --------
define('_ 주소', '주소');
define('_phone', 'Phone');
define('_ 이메일', '이메일');
define('_hovaten', '성명');
define('_chude', '나사');
define('_noidung', '콘텐츠');
define('_ghichu', '최신 정보를 받으려면 이메일 주소를 남겨주세요.');
//----------------------gio hang -----------------------------------
define('_thutu', '주문');
define('_tengh', '이름');
define('_gia', '가격');
define('_tonggia', '총 가격');
define('_tonggiaban', '총 가격');
define('_xoa', '삭제');
define('_muatiep', '다음 구매');
define('_tieptuc', '계속');
define('_xoatatca', '모두 삭제');
define('_capnhat', '업데이트');
define('_thanhtoan', '지불');
define('_soluong', '수량');
define('_thongbao', '장바구니에 상품이 없습니다!');
//-----------------------------------------------------
define('_spchitiet', '제품 정보');
define('_thongso', '사양');
define('_ungdung', '응용 프로그램');
define('_ykien', '댓글');
define('_mausac', '컬러');
define('_dactrung', '추천 기능');
define('_hinhanh', '사진 라이브러리');
define('_kythuat', '기술적');
define('_khachhang', '고객');
define('_lapdat', '설치');
define('_pt1', '결제 수단');
define('_pt2', '방법');
define('_pt3', '결제 방법 선택');
define('_pt4', '현금 결제');
define('_pt5', '포스트 송금');
define('_pt6', 'ATM 전송');

define('_xacnhan', '확인');
define('_xoa', '삭제');
?>