<?php
return array(
'title_main',
'config_photo',
'config_images',
'config_mota',
'config_noidung',
'config_list',
'config_cat',
'config_item',
'config_sub',
'config_giaban',
'config_giacu',
'config_noibat',
'config_noibat1',
'config_noibat2',
'config_noibat3',
'config_tags',
'config_link',
'ratio',
'_width_thumb',
'_height_thumb',
'_style_thumb'
);
